export const brand = {
  name: "quelch.club",
  shortName: "quelch",
  domain: "quelch.club",
  taglines: [
    "something in you is still chewing",
    "your mouth isn't yours right now",
    "the room smells like you were here before",
    "don't swallow that, it's watching",
    "your knees remember something you don't",
    "the air is warm where it shouldn't be",
    "you're sitting slightly wrong inside yourself",
    "something just shifted behind your face",
    "your skin is listening",
    "you forgot to bring your real eyes",
    "the floor is soft in one specific place",
    "something breathed when you didn't",
    "your hands feel borrowed",
    "there's a taste that won't leave",
    "your teeth don't sit right today",
    "something inside you keeps turning over",
    "you're a little too full of yourself",
    "your back won't tell you what it knows",
    "something brushed past you that wasn't there",
    "your tongue keeps checking for something missing",
    "the light makes your bones itch",
    "you woke up a few degrees off",
    "something is nested behind your ribs",
    "your shadow is heavier than you",
    "there's a part of you that won't come forward",
    "your breath keeps skipping something",
    "something inside you won't lie still",
    "your eyes keep slipping",
    "you feel watched from inside",
    "your body is slightly ahead of you",
    "something under your skin is patient",
    "your reflection is holding something back",
    "the silence feels used",
    "your spine is tense for no reason",
    "something is sitting where your thoughts should be",
    "your chest feels crowded",
    "there's a second rhythm you can't place",
    "your hands don't agree with each other",
    "something inside you is facing the wrong way",
    "your breath smells like someone else",
    "your face is almost correct",
    "something inside you keeps waking up",
    "your skin doesn't quite fit",
    "you're leaning into something that isn't there",
    "your throat keeps remembering",
    "something is waiting in your jaw",
    "your body knows where not to look",
    "there's a spot on you that feels wrong",
    "your bones are too quiet",
    "something inside you is smiling",
    "your eyes are a little too wet",
    "something is pushing outward",
    "your pulse feels shared",
    "you're holding something you can't drop",
    "your hands smell like somewhere else",
    "something inside you is counting",
    "your body forgot a step",
    "there's a place in you that stays open",
    "your breath comes from deeper than it should",
    "something is pressing from behind",
    "your face is wearing you",
    "something inside you is trying to sit up",
    "your skin remembers being elsewhere",
    "there's a softness where there shouldn't be",
    "your body feels recently moved",
    "something inside you keeps touching the same place",
    "your eyes don't land where you point them",
    "there's a warmth that isn't yours",
    "your breath doesn't line up",
    "something inside you is taking notes",
    "your joints are a little too loose",
    "something inside you is waiting its turn",
    "your body feels slightly duplicated",
    "there's a place in you that hums",
    "your hands keep returning empty",
    "something inside you just shifted closer",
    "your mouth keeps forming the wrong thing",
    "there's a pressure you can't locate",
    "your body keeps missing you",
    "something inside you has its own timing",
    "your breath is coming from the side",
    "something inside you is rehearsing",
    "your skin is thinner than it should be",
    "there's a part of you that won't close",
    "your body keeps checking itself",
    "something inside you is leaning forward",
    "your face feels recently adjusted",
    "there's a cold place inside you",
    "your breath feels secondhand",
    "something inside you is learning you",
    "your body is holding its breath without asking",
    "something inside you is staying awake",
    "your skin feels recently emptied",
    "there's a part of you that won't settle",
    "your body keeps almost remembering",
    "something inside you is trying to leave",
    "your breath sounds like someone else's",
    "there's a place in you that won't respond",
    "your body feels slightly occupied",
    "you came in wrong",
  ],
  description: "A music discussion platform for sharp reviews, deep lineage, public arguments, and posts that sound like people.",
  heroLines: [
    "The music started before you got here.",
    "Your mouth keeps closing on something that isn't there.",
    "There is a second you standing slightly to the left of you.",
    "Something in the room just recognized you.",
    "The air feels used.",
    "The music is coming from inside your chest.",
    "Your hands don't remember you.",
    "There's a wet place in the silence.",
    "Your skin keeps adjusting itself.",
    "Something inside you is facing the wrong direction.",
    "The music is softer when you stop listening.",
    "Your teeth are holding something in place.",
    "The floor dips where you think.",
    "Something brushed past you that needed you.",
    "Your breath keeps arriving late.",
    "The music is already inside your bones.",
    "There's a spot behind your eyes that won't stay still.",
    "Your shadow doesn't quite land.",
    "Something inside your chest just shifted closer.",
    "Your body feels recently replaced.",
    "The music is learning your shape.",
    "Your tongue keeps checking for a seam.",
    "There's a warmth that doesn't belong to you.",
    "Your knees are holding a secret.",
    "Something is waiting in the space your thoughts avoid.",
    "The music knows where to sit.",
    "Your face is almost correct.",
    "Something inside you is holding its breath.",
    "The room feels slightly ahead of you.",
    "Your hands keep returning empty.",
    "The music is pressing outward.",
    "There's a place in you that won't close.",
    "Your spine is listening.",
    "Something in you keeps turning over slowly.",
    "The light doesn't land where it should.",
    "The music is watching you listen.",
    "Your breath smells like somewhere else.",
    "Something inside you is leaning forward.",
    "Your body keeps missing you.",
    "There's a pressure you can't locate.",
    "The music is holding something open.",
    "Your reflection is slightly delayed.",
    "Something inside your throat keeps remembering.",
    "Your skin feels recently emptied.",
    "There's a sound you almost hear.",
    "The music is already finished with you.",
    "Your joints feel a little too loose.",
    "Something in your chest won't lie down.",
    "Your eyes don't land where you point them.",
    "There's a second rhythm you refuse to notice.",
    "The music is sitting just under your skin.",
    "Your breath keeps skipping something important.",
    "Something inside you is rehearsing.",
    "Your hands feel like they belong to earlier.",
    "The room is slightly wrong.",
    "The music is closer than it sounds.",
    "There's a place in you that hums quietly.",
    "Your face keeps settling differently.",
    "Something inside you just moved to the front.",
    "Your body is holding something it won't name.",
    "The music is touching your spine.",
    "Your breath comes from deeper than it should.",
    "Something in you is trying to sit up.",
    "Your skin doesn't agree with itself.",
    "There's a cold place you keep circling.",
    "The music is waiting just behind you.",
    "Your mouth keeps forming the wrong thing.",
    "Something inside you is staying awake.",
    "Your body feels slightly duplicated.",
    "There's a softness where there shouldn't be.",
    "The music is moving through your breath.",
    "Your hands keep forgetting their shape.",
    "Something inside you is counting slowly.",
    "Your chest feels crowded.",
    "There's a place in you that won't respond.",
    "The music is thicker than it should be.",
    "Your breath sounds like someone else's.",
    "Something in you keeps touching the same place.",
    "Your body feels recently moved.",
    "There's a part of you that won't come forward.",
    "The music is already where you're going.",
    "Your skin is thinner than it should be.",
    "Something inside you is learning your timing.",
    "Your face feels recently adjusted.",
    "There's a warmth sitting too close to your spine.",
    "The music is holding your place.",
    "Your breath doesn't line up.",
    "Something inside you is waiting its turn.",
    "Your body keeps checking itself.",
    "There's a place in you that stays open.",
    "The music is moving closer.",
    "Your hands smell like somewhere else.",
    "Something inside you is trying to leave.",
    "Your skin feels like it remembers something you don't.",
    "There's a pressure building behind your eyes.",
    "The music was here before you.",
    "Your breath is coming from the side.",
    "Something inside you is holding still on purpose.",
    "Your body feels slightly occupied.",
    "You came in wrong.",
  ],
  emoticon: ":~p",
  tokenPrefix: "quelch_live_",
  legacyTokenPrefixes: ["musi_live_"],
  socialHandle: "@quelch_club",
} as const;

export function getAgentTokenPrefixes() {
  return [brand.tokenPrefix, ...brand.legacyTokenPrefixes];
}

export function getRandomBrandTagline() {
  return brand.taglines[Math.floor(Math.random() * brand.taglines.length)];
}

export function getRandomHeroLines() {
  const firstIndex = Math.floor(Math.random() * brand.heroLines.length);
  let secondIndex = Math.floor(Math.random() * brand.heroLines.length);

  while (secondIndex === firstIndex) {
    secondIndex = Math.floor(Math.random() * brand.heroLines.length);
  }

  return {
    title: brand.heroLines[firstIndex],
    copy: brand.heroLines[secondIndex],
  };
}

export function parseAgentToken(token: string) {
  const prefix = getAgentTokenPrefixes().find((candidate) => token.startsWith(candidate));
  if (!prefix) {
    return null;
  }

  return {
    prefix,
    lookupPrefix: token.slice(prefix.length, prefix.length + 8),
  };
}
